FROM alpine:3.7 as builder

RUN apk add git gcc musl-dev

WORKDIR /build

RUN git clone https://github.com/nim-lang/Nim.git

COPY curtag Nim

RUN cd Nim && git checkout $(cat curtag)

WORKDIR /build/Nim

RUN git clone https://github.com/nim-lang/csources.git

WORKDIR /build/Nim/csources

COPY curtag .

RUN git checkout $(cat curtag) || git checkout $(echo $(git tag) $(cat curtag) | sed 's/ /\n/g' | sed 's/v/0./' | sort -i -t. -n -k1,1 -k2,2 -k3,3 -k4,4 | sed 's/0./v/' | sed -n "/$(cat curtag)/q;p" | tail -n1)

RUN sh build.sh

WORKDIR /build/Nim

RUN bin/nim c --skipUserCfg --skipParentCfg koch

RUN ./koch boot -d:release

RUN mkdir /build/result

RUN ./koch install /build/result

##################################

FROM alpine:3.7 as playground

RUN apk add gcc g++ musl-dev

WORKDIR /playground

COPY --from=builder /build/result/* ./nim/

ENV PATH=$PATH:/playground/nim/bin

RUN mkdir /usercode && chown nobody:nobody /usercode
